// FIXME License notice

#ifndef ACTIONS_HH
#define ACTIONS_HH

enum action_id {
    ID_ACTION_CAPTURER,
    ID_ACTION_LIER,
    ID_ACTION_ATTAQUER,
    ID_ACTION_DEPLACER,
    ID_ACTION_RECHARGER,
    ID_ACTION_AJOUTER_BOUCLIER,
    ID_ACTION_UTILISER_VIRUS,
    ID_ACTION_UTILISER_TURBO
};

#endif // !ACTIONS_HH
